CREATE TABLE suppliers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT null,
    CONSTRAINT pk_suplier PRIMARY KEY (id)
);
CREATE TABLE products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    typeof VARCHAR(50) NOT null,
    price DECIMAL(10, 2) NOT NULL,
    supplier_id INTEGER NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id),
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
);
CREATE TABLE supply (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    supplier_id BIGINT NOT NULL,
    supply_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_supply PRIMARY KEY (id),
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
);
   CREATE TABLE IF NOT EXISTS supply_products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    supply_id INTEGER REFERENCES supply (id) ON DELETE CASCADE,
    product_id INTEGER REFERENCES products (id) ON DELETE CASCADE,
    amount DECIMAL(10, 2) NOT NULL,
    CONSTRAINT pk_sp PRIMARY KEY (id)
    );

INSERT INTO suppliers (name)
VALUES ('YablochkiDushistie');
INSERT INTO suppliers (name)
VALUES ('GrushiKrasnie');

INSERT INTO products (name, typeof, price, supplier_id)
VALUES ('Яблоко 1', 'Яблоко', 50, 1);
INSERT INTO products (name, typeof, price, supplier_id)
VALUES ('Яблоко 2', 'Яблоко', 50, 1);
INSERT INTO products (name, typeof, price, supplier_id)
VALUES ('Груша 1', 'Груша', 50, 2);
INSERT INTO Products (name, typeof, price, supplier_id)
VALUES ('Груша 2', 'Груша', 50, 2);